### ISSUE TITLE
[Update] EndOfDayCountdown V2

### ISSUE THREAD

**Issue by Koishukaze** [Friskzips/LC-FacilityMeltdown-End-of-day-countdown-compatibility#1]
Should update to use https://thunderstore.io/c/lethal-company/p/NotezyTeam/EndOfDayCountdown_V2/ instead as the previous one is deprecated

**Comment by Friskzips** [comment]
Ok, sadly im kinda busy gonna fix it on 6 hours.

**Comment by Friskzips** [comment]
ok done, thanks for the report.
